spring:
  application:
    name: timetracker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

security:
  secret-key: uPqvl1XJ7NpiKw4xZJB9htmwoDAgfnOFRlO3o6PIBDE=

validation:
  name-pattern: "^[a-zA-Z0-9]+$"

