name: CI for timetracker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run unit tests only
        run: mvn test -Dtest=unit
